"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import Script from "next/script";
import {
  HiCheckCircle,
  HiArrowRight,
  HiSparkles,
  HiChevronDown,
  HiBolt,
  HiChartBar,
  HiCog6Tooth,
  HiCircleStack,
  HiUserGroup,
  HiRocketLaunch,
  HiEnvelope,
  HiMagnifyingGlass,
  HiClipboardDocumentList,
} from "react-icons/hi2";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import {
  BookingSection,
  BookingBanner,
  FloatingBookingButton,
  BOOKING_URL,
} from "../../components/booking-cta";

/* ═══════════════════════════════════════════════════════════════════════════
   DATA
═══════════════════════════════════════════════════════════════════════════ */

const METRICS = [
  { metric: "4.2×", label: "More Pipeline Generated", sub: "vs traditional outreach methods" },
  { metric: "80%", label: "Less Manual Outreach Work", sub: "time saved for sales teams" },
  { metric: "92%", label: "CRM Data Accuracy", sub: "auto-updated from every interaction" },
  { metric: "3 Weeks", label: "To Full Deployment", sub: "from kickoff to live pipeline" },
];

const CAPABILITIES = [
  {
    icon: HiMagnifyingGlass,
    title: "AI Prospecting",
    desc: "Automated prospect discovery using intent signals, firmographic filters, and technographic data. AI identifies best-fit accounts from Apollo, LinkedIn, and web sources matching your ICP in real time.",
  },
  {
    icon: HiEnvelope,
    title: "Personalized Outreach",
    desc: "Hyper-personalized email and LinkedIn sequences generated by GPT-4 using prospect's recent activity, company news, and role context — every message reads as hand-crafted, at scale.",
  },
  {
    icon: HiClipboardDocumentList,
    title: "Lead Qualification",
    desc: "AI qualification models score inbound leads against your ICP criteria — budget, authority, need, timing — routing high-fit leads to AEs and low-fit leads to nurture sequences automatically.",
  },
  {
    icon: HiCircleStack,
    title: "CRM Auto-Updates",
    desc: "Bidirectional CRM sync ensures every email sent, call logged, and meeting booked is instantly reflected in HubSpot or Salesforce — no manual data entry for your sales team ever again.",
  },
  {
    icon: HiBolt,
    title: "Follow-Up Sequences",
    desc: "Intelligent multi-touch follow-up sequences that adapt cadence and messaging based on prospect engagement signals — opens, clicks, replies, and LinkedIn profile visits.",
  },
  {
    icon: HiChartBar,
    title: "Sales Analytics & Reporting",
    desc: "Real-time pipeline dashboards tracking reply rates, meeting book rates, sequence performance, and pipeline velocity — connected directly to your CRM and outreach tooling.",
  },
];

const PROCESS = [
  {
    step: "01",
    title: "ICP Definition",
    desc: "We work with your sales team to define your Ideal Customer Profile in precise, machine-readable terms — industry, company size, technology stack, growth signals, and buying triggers. This ICP powers all downstream AI prospecting and qualification.",
  },
  {
    step: "02",
    title: "Data Enrichment",
    desc: "We connect Apollo.io, LinkedIn, and data enrichment APIs to continuously source and enrich prospect records with verified emails, direct dials, LinkedIn URLs, company tech stack, recent funding, and headcount signals.",
  },
  {
    step: "03",
    title: "Outreach Personalization",
    desc: "GPT-4 generates personalized outreach variants for each prospect using company news, role context, and pain-point mapping. We A/B test subject lines, openers, and CTAs to continuously improve response rates.",
  },
  {
    step: "04",
    title: "CRM Integration",
    desc: "Full bidirectional integration with HubSpot or Salesforce — contacts, deals, activities, and notes sync automatically. We map your existing pipeline stages and ensure zero disruption to your current workflow.",
  },
  {
    step: "05",
    title: "Performance Optimization",
    desc: "After go-live, we monitor reply rates, booking rates, and pipeline contribution weekly. We retune AI models, adjust sequence timing, and refine ICP definitions based on conversion data from your live pipeline.",
  },
];

const TECH = [
  { n: "OpenAI GPT-4", c: "bg-emerald-50 border-emerald-200 text-emerald-700" },
  { n: "Claude", c: "bg-violet-50 border-violet-200 text-violet-700" },
  { n: "Apollo.io", c: "bg-orange-50 border-orange-200 text-orange-700" },
  { n: "HubSpot", c: "bg-amber-50 border-amber-200 text-amber-700" },
  { n: "Salesforce", c: "bg-sky-50 border-sky-200 text-sky-700" },
  { n: "n8n", c: "bg-indigo-50 border-indigo-200 text-indigo-700" },
  { n: "LangChain", c: "bg-teal-50 border-teal-200 text-teal-700" },
  { n: "FastAPI", c: "bg-cyan-50 border-cyan-200 text-cyan-700" },
];

const INDUSTRIES = [
  { name: "SaaS", use: "Automated SDR workflows, trial-to-paid outreach sequences, churn risk re-engagement, expansion opportunity detection" },
  { name: "Insurance", use: "Policy renewal outreach, cross-sell campaigns, broker relationship management, lead scoring for inbound requests" },
  { name: "Real Estate", use: "Seller prospecting automation, buyer nurture sequences, property inquiry qualification, agent follow-up pipelines" },
  { name: "Finance", use: "Wealth management prospect outreach, compliance-checked messaging, AUM-based segmentation, advisor capacity matching" },
  { name: "Logistics", use: "Freight broker prospecting, shipper qualification, lane-based outreach personalization, carrier recruitment automation" },
  { name: "Healthcare", use: "Practice outreach for healthcare SaaS, provider onboarding sequences, compliance-aware email generation, referral pipeline automation" },
];

const WHY = [
  {
    title: "Sales + AI Expertise",
    desc: "We combine deep sales process knowledge with AI engineering. We've studied hundreds of B2B sales motions and translate your sales playbook into automated, AI-driven workflows — not generic templates.",
  },
  {
    title: "CRM-Native Integrations",
    desc: "We build native integrations with HubSpot and Salesforce — not Zapier workarounds. Every contact, activity, and pipeline update syncs in real time with full field mapping to your existing data model.",
  },
  {
    title: "Personalization at Scale",
    desc: "Our AI outreach generates messages that read as genuinely personal — using prospect-specific context like recent LinkedIn posts, company funding, and product launches. Not just mail-merge.",
  },
  {
    title: "Compliance-First Messaging",
    desc: "Every outreach sequence includes unsubscribe handling, CAN-SPAM compliance, email warm-up management, and domain reputation monitoring to protect your sending infrastructure.",
  },
  {
    title: "Measured Pipeline Impact",
    desc: "We tie our work to pipeline metrics — qualified meetings booked, pipeline dollar value generated, and cost per opportunity. You know exactly what the automation is delivering within 30 days.",
  },
];

const FAQS = [
  {
    q: "What is AI sales automation and how does it work?",
    a: "AI sales automation uses large language models (LLMs) like GPT-4 and workflow automation tools to replace manual, repetitive sales development tasks. This includes automated prospect sourcing from data providers like Apollo.io, AI-generated personalized outreach emails and LinkedIn messages, automated lead scoring and qualification against your ICP, CRM data entry and pipeline updates, and intelligent follow-up sequence execution — all running 24/7 without human intervention at each step.",
  },
  {
    q: "Can AI sales automation replace my SDR team?",
    a: "AI sales automation replaces the repetitive, low-value tasks SDRs currently spend 60-70% of their time on: prospect research, data entry, first-touch outreach, and follow-up cadences. This frees your SDRs (or reduces the headcount needed) to focus on high-value activities like discovery calls, objection handling, and relationship building. Most teams see 3-4× the output from the same headcount rather than replacing all SDRs.",
  },
  {
    q: "How does AI personalize outreach at scale without it sounding generic?",
    a: "We build personalization pipelines that enrich each prospect record with specific, individual context before any message is generated: recent LinkedIn activity, company funding news, technology stack changes, new job postings, executive hires, and product launches. GPT-4 then uses this context to write an opening line and value proposition that references something real and specific to that prospect — which is why AI-personalized outreach at scale consistently outperforms generic template-based messaging.",
  },
  {
    q: "Which CRMs do you integrate with?",
    a: "We build native integrations with HubSpot and Salesforce — including contact creation, deal creation, activity logging, lifecycle stage updates, and custom field mapping. We also integrate with Pipedrive, Close.io, and custom CRM databases. The integration is bidirectional: outreach actions write back to the CRM, and CRM data (like deal stage changes) can trigger or pause outreach sequences.",
  },
  {
    q: "How long does it take to see results from AI sales automation?",
    a: "Most clients see initial pipeline impact within 2-3 weeks of deployment: the first automated sequences launch, replies come in, and meetings begin booking. Meaningful pipeline data accumulates over 30-60 days as sequences mature and personalization models improve. Full ROI visibility — comparing pipeline generated to cost of automation — is typically clear by 60-90 days post-launch.",
  },
  {
    q: "Will AI outreach hurt our email domain reputation?",
    a: "Protecting domain reputation is a core part of our implementation. We set up dedicated sending domains (separate from your main business domain), configure proper SPF/DKIM/DMARC authentication, implement email warm-up protocols for new domains, enforce sending limits per mailbox, monitor bounce rates and spam complaint rates, and implement smart unsubscribe handling. We will not launch outreach sequences until your infrastructure meets deliverability benchmarks.",
  },
  {
    q: "Can the system handle inbound lead qualification too?",
    a: "Yes. Inbound qualification is often more impactful than outbound automation. When a lead fills out a form or books a demo, the AI immediately enriches the record, scores it against your ICP, triggers a personalized acknowledgment email, routes high-fit leads to AEs with enriched context, and places low-fit leads into nurture sequences — all within seconds of form submission, eliminating the response time gap that kills inbound conversion rates.",
  },
  {
    q: "How is AI sales automation different from tools like Outreach or Salesloft?",
    a: "Outreach and Salesloft are excellent sequence management platforms, but they require humans to research prospects, write messages, enrich data, and update the CRM. AI sales automation layers intelligence on top of (or instead of) these tools: it sources and qualifies prospects automatically, writes and personalizes messages without templates, enriches data continuously, and updates your CRM without any SDR involvement. We often integrate AI automation with existing Outreach/Salesloft instances rather than replacing them.",
  },
  {
    q: "What data sources do you use for prospect discovery?",
    a: "Our default stack uses Apollo.io (450M+ contact records with direct dials and verified emails), LinkedIn Sales Navigator (for intent signals and network data), Clearbit or Lusha for additional enrichment, and news APIs for company-level intent signals like funding announcements and executive hires. For specific verticals we integrate niche data sources — healthcare provider databases, insurance agency registries, property ownership records — depending on your ICP.",
  },
  {
    q: "How do you ensure AI-generated messages meet compliance requirements?",
    a: "Every outreach template and AI-generated message is reviewed against CAN-SPAM (US), GDPR (EU), and CASL (Canada) requirements before deployment. We implement mandatory unsubscribe links, sender identification, physical address footers, and suppression list management. For regulated industries (insurance, healthcare, finance), we add additional compliance layers — industry-specific disclaimers, content guardrails in the AI prompt, and human review gates for high-risk message types.",
  },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map(({ q, a }) => ({
    "@type": "Question",
    name: q,
    acceptedAnswer: { "@type": "Answer", text: a },
  })),
};

const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "AI Sales Automation",
  provider: {
    "@type": "Organization",
    name: "Infonza Innovations",
    url: "https://infonza.com",
  },
  description:
    "Automate your entire sales process with AI — prospecting, personalized outreach, lead qualification, CRM updates, and follow-up sequences that run 24/7.",
  areaServed: "Worldwide",
  serviceType: "AI Automation",
  url: "https://infonza.com/ai-solutions/sales-automation",
};

/* ═══════════════════════════════════════════════════════════════════════════
   COMPONENTS
═══════════════════════════════════════════════════════════════════════════ */

function FAQItem({ q, a, index }) {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4, delay: index * 0.07 }}
      className="border border-slate-200 rounded-xl overflow-hidden"
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left hover:bg-slate-50 transition-colors"
      >
        <span className="font-semibold text-slate-900 text-sm sm:text-base">{q}</span>
        <motion.div animate={{ rotate: open ? 180 : 0 }} transition={{ duration: 0.25 }}>
          <HiChevronDown className="w-5 h-5 text-slate-400 flex-shrink-0" />
        </motion.div>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
          >
            <p className="px-6 pb-5 text-slate-600 text-sm leading-relaxed border-t border-slate-100 pt-4">
              {a}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   PAGE
═══════════════════════════════════════════════════════════════════════════ */

export default function SalesAutomationPage() {
  return (
    <>
      <Script
        id="faq-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Script
        id="service-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }}
      />
      <Navbar />

      {/* ── HERO ── */}
      <section className="relative bg-slate-900 overflow-hidden pt-24 pb-20 lg:pt-32 lg:pb-28">
        <div className="absolute inset-0 bg-grid opacity-40" />
        <div className="absolute top-0 right-0 w-[600px] h-[400px] bg-teal-600/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-sm text-slate-500 mb-8">
            <Link href="/" className="hover:text-teal-400 transition-colors">Home</Link>
            <span>/</span>
            <Link href="/ai-solutions" className="hover:text-teal-400 transition-colors">AI Solutions</Link>
            <span>/</span>
            <span className="text-slate-300 font-medium">AI Sales Automation</span>
          </div>

          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Left */}
            <motion.div
              initial={{ opacity: 0, y: 32 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 bg-teal-900/60 border border-teal-700/40 rounded-full px-4 py-1.5 text-teal-300 text-xs font-semibold uppercase tracking-widest mb-6">
                <HiRocketLaunch className="w-3.5 h-3.5" />
                AI Sales Automation
              </div>
              <h1 className="text-4xl sm:text-5xl font-bold text-white leading-[1.1] mb-6">
                Automate Your Sales Pipeline{" "}
                <span className="text-gradient">With AI</span>
              </h1>
              <p className="text-lg text-slate-400 leading-relaxed mb-8 max-w-xl">
                We build AI-powered sales automation systems that prospect, qualify, personalize
                outreach, update your CRM, and follow up — 24/7, without your team lifting a finger.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <a
                  href={BOOKING_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-center gap-2 px-7 py-4 rounded-xl bg-gradient-to-r from-teal-600 to-blue-600 text-white font-semibold hover:opacity-90 transition-all hover:shadow-2xl hover:shadow-teal-500/30 hover:-translate-y-0.5"
                >
                  Schedule Free Consultation <HiArrowRight className="w-4 h-4" />
                </a>
                <Link
                  href="/case-studies"
                  className="inline-flex items-center justify-center gap-2 px-7 py-4 rounded-xl border border-slate-700 text-slate-300 font-semibold hover:border-slate-500 hover:text-white transition-all"
                >
                  View Case Studies
                </Link>
              </div>
            </motion.div>

            {/* Right — pipeline visualization */}
            <motion.div
              initial={{ opacity: 0, x: 40 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.7, delay: 0.15 }}
            >
              <div className="bg-slate-800/80 border border-slate-700/60 rounded-2xl overflow-hidden shadow-2xl">
                <div className="flex items-center gap-3 px-5 py-3.5 border-b border-slate-700/60 bg-slate-800">
                  <div className="w-2 h-2 rounded-full bg-teal-400 animate-pulse" />
                  <span className="text-sm font-medium text-slate-200">Sales Automation — Running</span>
                  <span className="ml-auto text-xs text-slate-500">GPT-4 + Apollo</span>
                </div>
                <div className="p-5 space-y-3 min-h-[280px] font-mono text-xs">
                  {[
                    { status: "done", label: "Prospect sourced", detail: "47 ICP-matched contacts from Apollo.io — SaaS CTOs, 50-500 employees" },
                    { status: "done", label: "Data enriched", detail: "LinkedIn URLs, verified emails, company funding confirmed for all 47" },
                    { status: "done", label: "Personalization", detail: "GPT-4 generated opening lines using LinkedIn posts + recent company news" },
                    { status: "done", label: "Outreach sent", detail: "47 personalized emails dispatched — 12 opens detected within 2h" },
                    { status: "active", label: "Follow-up queued", detail: "Day-3 follow-up sequence staged for 35 non-responders…" },
                    { status: "pending", label: "CRM sync", detail: "HubSpot contacts + deal records awaiting reply detection" },
                  ].map((step, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <div className={`w-2 h-2 rounded-full mt-1 flex-shrink-0 ${
                        step.status === "done" ? "bg-teal-400" :
                        step.status === "active" ? "bg-orange-400 animate-pulse" :
                        "bg-slate-600"
                      }`} />
                      <div>
                        <span className={`font-semibold ${
                          step.status === "done" ? "text-teal-400" :
                          step.status === "active" ? "text-orange-400" :
                          "text-slate-500"
                        }`}>[{step.label}]</span>
                        <span className="text-slate-400 ml-2">{step.detail}</span>
                      </div>
                    </div>
                  ))}
                </div>
                <div className="px-5 py-3 border-t border-slate-700/60 flex items-center justify-between">
                  <span className="text-xs text-slate-500">Pipeline added: $182,000 this week</span>
                  <span className="text-xs text-teal-400">3 meetings booked today</span>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── METRICS ── */}
      <section className="bg-white py-12 border-b border-slate-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {METRICS.map((r, i) => (
              <motion.div
                key={r.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
              >
                <div className="text-3xl sm:text-4xl font-bold text-gradient mb-1">{r.metric}</div>
                <div className="font-semibold text-slate-900 text-sm">{r.label}</div>
                <div className="text-xs text-slate-400 mt-0.5">{r.sub}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CAPABILITIES ── */}
      <section className="bg-dots bg-white py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              What We Automate in Your{" "}
              <span className="text-gradient">Sales Process</span>
            </h2>
            <p className="text-slate-500 max-w-xl mx-auto">
              Six core sales automation capabilities delivered in every system we build and deploy.
            </p>
          </motion.div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
            {CAPABILITIES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.07 }}
                className="bg-white border border-slate-200 rounded-xl p-5 hover:border-teal-300 hover:shadow-lg transition-all"
              >
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-teal-600 to-blue-600 flex items-center justify-center mb-3">
                  <f.icon className="w-5 h-5 text-white" />
                </div>
                <h3 className="font-bold text-slate-900 text-sm mb-1.5">{f.title}</h3>
                <p className="text-xs text-slate-500 leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PROCESS ── */}
      <section className="relative bg-slate-900 py-20 lg:py-24 overflow-hidden">
        <div className="absolute inset-0 bg-grid opacity-40" />
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-white mb-3">
              How We Build Your <span className="text-gradient">Sales Automation</span>
            </h2>
            <p className="text-slate-400">From ICP definition to live pipeline in 3 weeks.</p>
          </motion.div>
          <div className="space-y-4">
            {PROCESS.map((s, i) => (
              <motion.div
                key={s.step}
                initial={{ opacity: 0, x: -24 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="flex gap-5 p-5 rounded-xl bg-slate-800/60 border border-slate-700/60 hover:border-teal-700/60 transition-colors"
              >
                <div className="flex-shrink-0 w-11 h-11 rounded-xl bg-gradient-to-br from-teal-600 to-blue-600 flex items-center justify-center text-white font-bold text-xs font-mono">
                  {s.step}
                </div>
                <div>
                  <h3 className="font-bold text-white text-sm mb-1">{s.title}</h3>
                  <p className="text-slate-400 text-sm leading-relaxed">{s.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── TECH STACK ── */}
      <section className="bg-slate-50 py-12 border-y border-slate-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h3 className="text-lg font-bold text-slate-900 mb-5">Technology Stack</h3>
          <div className="flex flex-wrap justify-center gap-2.5">
            {TECH.map(({ n, c }) => (
              <span key={n} className={`px-3.5 py-1.5 rounded-full border text-xs font-semibold ${c}`}>
                {n}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── INDUSTRIES ── */}
      <section className="bg-white py-20 lg:py-24">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-slate-900 mb-3">
              AI Sales Automation Across <span className="text-gradient">Industries</span>
            </h2>
            <p className="text-slate-500 max-w-xl mx-auto">
              We build sales automation tailored to your industry's buying cycles, compliance needs, and data sources.
            </p>
          </motion.div>
          <div className="grid md:grid-cols-2 gap-4">
            {INDUSTRIES.map((ind, i) => (
              <motion.div
                key={ind.name}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.07 }}
                className="flex gap-4 p-4 rounded-xl bg-slate-50 border border-slate-200 hover:border-teal-200 transition-colors"
              >
                <div className="flex-shrink-0 w-8 h-8 rounded-lg bg-teal-50 border border-teal-100 flex items-center justify-center">
                  <HiCheckCircle className="w-4 h-4 text-teal-600" />
                </div>
                <div>
                  <p className="font-semibold text-slate-900 text-sm mb-0.5">{ind.name}</p>
                  <p className="text-xs text-slate-500 leading-relaxed">{ind.use}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── WHY INFONZA ── */}
      <section className="bg-slate-50 py-16 lg:py-20 border-y border-slate-100">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-slate-900 mb-3">
              Why Teams Choose <span className="text-gradient">Infonza</span> for Sales Automation
            </h2>
          </motion.div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
            {WHY.map((w, i) => (
              <motion.div
                key={w.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="bg-white border border-slate-200 rounded-xl p-5 hover:border-teal-200 hover:shadow-md transition-all"
              >
                <HiCheckCircle className="w-6 h-6 text-teal-500 mb-3" />
                <h3 className="font-bold text-slate-900 text-sm mb-2">{w.title}</h3>
                <p className="text-xs text-slate-500 leading-relaxed">{w.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── BOOKING BANNER ── */}
      <section className="py-12 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <BookingBanner
            heading="Want to see the pipeline impact before committing?"
            subheading="Get a free sales automation audit from our team. We'll map your current process, identify the highest-ROI automation opportunities, and give you a realistic scope."
            cta="Schedule Free Sales Audit"
          />
        </div>
      </section>

      {/* ── RELATED SERVICES ── */}
      <section className="bg-slate-50 py-14 border-t border-slate-100">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-8 text-center">
            Related Services
          </h2>
          <div className="grid md:grid-cols-3 gap-5">
            {[
              {
                title: "AI Lead Generation Automation",
                desc: "Build an AI-powered lead generation engine that scrapes, qualifies, enriches, and launches outreach to thousands of prospects daily.",
                href: "/ai-solutions/lead-generation-automation",
                icon: HiMagnifyingGlass,
              },
              {
                title: "AI CRM Automation",
                desc: "Automate CRM data entry, deal progression, activity logging, and pipeline reporting with AI that integrates natively with HubSpot and Salesforce.",
                href: "/ai-solutions/crm-automation",
                icon: HiCircleStack,
              },
              {
                title: "AI Email Automation",
                desc: "AI-driven email sequences that personalize at scale, adapt to engagement signals, and optimize send timing for maximum reply rates.",
                href: "/ai-solutions/email-automation",
                icon: HiEnvelope,
              },
            ].map((s, i) => (
              <motion.div
                key={s.href}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
              >
                <Link
                  href={s.href}
                  className="group flex flex-col h-full bg-white border border-slate-200 rounded-xl p-5 hover:border-teal-300 hover:shadow-lg transition-all"
                >
                  <div className="w-9 h-9 rounded-lg bg-teal-50 border border-teal-100 flex items-center justify-center mb-3 group-hover:bg-teal-100 transition-colors">
                    <s.icon className="w-4 h-4 text-teal-600" />
                  </div>
                  <h3 className="font-bold text-slate-900 text-sm mb-1.5 group-hover:text-teal-700 transition-colors">
                    {s.title}
                  </h3>
                  <p className="text-xs text-slate-500 flex-1 leading-relaxed">{s.desc}</p>
                  <div className="mt-3 flex items-center gap-1 text-teal-600 text-xs font-semibold">
                    Learn more <HiArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="bg-white py-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-slate-900 mb-3">
              Frequently Asked Questions
            </h2>
            <p className="text-slate-500">
              Honest answers to the questions sales leaders ask before automating their pipeline.
            </p>
          </motion.div>
          <div className="space-y-3">
            {FAQS.map((f, i) => (
              <FAQItem key={i} {...f} index={i} />
            ))}
          </div>
        </div>
      </section>

      <BookingSection
        badge="Free Sales Consultation"
        heading="Start Generating More Pipeline With AI"
        subheading="Schedule a 30-minute session with our sales automation engineers. We'll review your current sales process, identify the biggest automation wins, and give you a realistic timeline and ROI estimate before you commit."
        primaryCTA="Schedule Free Consultation"
        secondaryCTA="Talk to a Sales Automation Expert"
      />

      <FloatingBookingButton label="Book Consultation" />
      <Footer />
    </>
  );
}
