import {
  /* Industry badge icons */
  HiAcademicCap,
  HiBeaker,
  HiBanknotes,
  HiShoppingCart,
  HiHome,
  HiHeart,
  HiTruck,
  HiGlobeAlt,
  HiWrenchScrewdriver,
  HiFilm,
  /* Solution / pain-point / stat icons */
  HiComputerDesktop,
  HiDevicePhoneMobile,
  HiCpuChip,
  HiCircleStack,
  HiCloud,
  HiChartBar,
  HiDocumentText,
  HiUserGroup,
  HiShieldCheck,
  HiServerStack,
  HiBolt,
  HiSparkles,
  HiCalendarDays,
  HiRocketLaunch,
  HiCodeBracket,
  HiStar,
  HiClock,
  HiCurrencyDollar,
  HiChartBarSquare,
  HiUsers,
  HiMapPin,
  HiLightBulb,
} from "react-icons/hi2";

/* ── Cross-industry pill navigation ─────────────────────────────────────── */
export const ALL_INDUSTRY_LINKS = [
  { href: "/industries/education",          label: "Education" },
  { href: "/industries/food-beverage",      label: "Food & Beverage" },
  { href: "/industries/finance",            label: "Finance" },
  { href: "/industries/retail-ecommerce",   label: "Retail & eCommerce" },
  { href: "/industries/real-estate",        label: "Real Estate" },
  { href: "/industries/healthcare",         label: "Healthcare" },
  { href: "/industries/transport-logistics",label: "Transport & Logistics" },
  { href: "/industries/travel-hospitality", label: "Travel & Hospitality" },
  { href: "/industries/manufacturing",      label: "Manufacturing" },
  { href: "/industries/media-entertainment",label: "Media & Entertainment" },
];

/* ── Industry configs ────────────────────────────────────────────────────── */
export const INDUSTRY_CONFIGS = {

  /* ── Education ─────────────────────────────────────────────────────────── */
  "education": {
    slug: "education",
    label: "Education",
    badgeText: "EdTech Specialists",
    badgeIcon: HiAcademicCap,
    headline: "Custom Education Software & EdTech Platform Development",
    subheadline: "From LMS and student portals to AI-powered tutoring tools — we build scalable EdTech platforms that improve learning outcomes and reduce administrative burden for schools, universities, and online learning companies.",
    heroVisual: {
      title: "EdTech Platform Dashboard",
      subtitle: "Live Learning Analytics",
      mainStat: "2.1M+",
      mainStatLabel: "Students on Platforms We've Built",
      metrics: [
        { label: "Student Retention", value: "89%" },
        { label: "Course Completion", value: "78%" },
        { label: "Admin Time Saved", value: "65%" },
        { label: "Platform Uptime", value: "99.9%" },
      ],
    },
    trustStats: [
      { value: "30+", label: "EdTech Platforms Delivered", icon: HiRocketLaunch },
      { value: "2M+", label: "Students Served Globally", icon: HiUsers },
      { value: "65%", label: "Average Admin Time Saved", icon: HiClock },
      { value: "FERPA", label: "Compliant by Design", icon: HiShieldCheck },
    ],
    solutions: [
      { icon: HiComputerDesktop, title: "Learning Management System (LMS)", description: "Multi-tenant, SCORM-compliant LMS platforms with course authoring, progress tracking, certificates, and deep analytics — built to scale from 500 to 500,000 learners.", href: "/saas-development/multi-tenant-saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiCircleStack, title: "Student Information System", description: "Unified SIS covering enrollment, grades, scheduling, attendance, and reporting — replacing spreadsheets and legacy systems with one integrated, FERPA-compliant platform.", href: "/erp-development/custom-erp-solutions", color: "from-blue-500 to-indigo-500" },
      { icon: HiDevicePhoneMobile, title: "E-Learning Mobile Apps", description: "iOS and Android learning apps with offline mode, push notifications, gamification, and live class support — giving students a seamless experience on any device.", href: "/staff-augmentation/hire-react-native-developers", color: "from-violet-500 to-purple-500" },
      { icon: HiCpuChip, title: "AI-Powered Tutoring & Assessment", description: "Adaptive learning engines, AI essay graders, automated quiz generation, and personalized learning path recommendations powered by LLMs and RAG pipelines.", href: "/ai-development", color: "from-orange-500 to-amber-500" },
      { icon: HiCloud, title: "Virtual Classroom Platform", description: "Real-time collaboration platforms with video, whiteboard, breakout rooms, and recording — purpose-built for K-12, higher education, and corporate training.", href: "/saas-development", color: "from-rose-500 to-pink-500" },
      { icon: HiDocumentText, title: "Admissions & Enrollment System", description: "End-to-end admissions workflows covering applications, document collection, review pipelines, acceptance/rejection automation, and enrollment confirmation.", href: "/erp-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiDocumentText, title: "Manual Administrative Burden", description: "Educators spending 40–60% of their time on administrative tasks — grading, scheduling, attendance, reporting — instead of teaching. Manual processes cost institutions thousands of hours per year." },
      { icon: HiCircleStack, title: "Disconnected Systems", description: "SIS, LMS, billing, and communication tools that don't talk to each other. Students fall through the cracks, staff re-key the same data across platforms, and reporting is always out of sync." },
      { icon: HiUsers, title: "Poor Student Engagement", description: "In hybrid and online environments, engagement and completion rates plummet. Without interactive tools, progress tracking, and timely interventions, students disengage before they complete courses." },
      { icon: HiShieldCheck, title: "FERPA & COPPA Compliance Complexity", description: "Managing student data privacy across vendors, cloud providers, and third-party tools — while staying ahead of evolving FERPA requirements and COPPA obligations for under-13 users — is a constant liability." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "AWS", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "WebRTC", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "Twilio", color: "bg-red-100 text-red-700 border-red-200" },
      { label: "Stripe", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "React Native", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "SCORM / xAPI", color: "bg-slate-100 text-slate-700 border-slate-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
    ],
    relatedServices: [
      { title: "Multi-Tenant SaaS Development", description: "Build LMS platforms and EdTech SaaS products that serve thousands of institutions from a single codebase.", href: "/saas-development", tag: "SaaS Development" },
      { title: "AI & LLM Development", description: "Add intelligent tutoring, adaptive assessments, and personalized learning paths powered by production-grade AI.", href: "/ai-development", tag: "AI Development" },
      { title: "Hire EdTech Engineers", description: "Augment your team with dedicated engineers who have prior EdTech platform experience, available in 72 hours.", href: "/staff-augmentation", tag: "Staff Augmentation" },
    ],
    faqs: [
      { q: "How long does it take to build a custom LMS?", a: "A focused MVP LMS — core course management, learner portal, and progress tracking — typically takes 10–14 weeks. A full-featured platform with AI tutoring, mobile apps, integrations, and white-labeling is a 4–6 month engagement. We provide a detailed milestone roadmap after discovery." },
      { q: "Can you integrate with Google Classroom, Canvas, or Blackboard?", a: "Yes. We've built integrations with Google Classroom, Canvas, Moodle, Blackboard, Brightspace, and custom SCORM/xAPI systems. Integration scope depends on the specific API capabilities of the platform. We map this during discovery." },
      { q: "How do you handle FERPA and COPPA compliance?", a: "We design data access controls, audit trails, and consent workflows aligned with FERPA requirements from the start. For COPPA-regulated products (under-13), we implement age verification and parental consent flows. We work with your legal counsel to ensure every system component meets current requirements." },
      { q: "Is a custom LMS better than configuring Moodle or Canvas?", a: "It depends on your requirements. If you need specific workflows, integrations, or a white-labeled product experience that off-the-shelf platforms can't support — custom is the right choice. We often help clients augment or extend existing LMS platforms rather than replace them, which is faster and more cost-effective." },
      { q: "What does EdTech software development cost?", a: "A focused module (enrollment system, learner portal) typically starts at $40K–$80K. A full EdTech platform with mobile apps, AI features, and integrations ranges from $150K–$400K+. You receive a fixed-price estimate after the free discovery session." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "30+", label: "EdTech projects" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "EdTech engineers on every call",
      "FERPA-compliant architecture review",
    ],
    floatingButtonLabel: "Book EdTech Consultation",
  },

  /* ── Food & Beverage ───────────────────────────────────────────────────── */
  "food-beverage": {
    slug: "food-beverage",
    label: "Food & Beverage",
    badgeText: "F&B Technology Experts",
    badgeIcon: HiBeaker,
    headline: "Custom Food & Beverage Software & Restaurant Technology",
    subheadline: "Online ordering platforms, POS integrations, inventory systems, and delivery apps built for restaurants, QSRs, food brands, and D2C food businesses — designed to cut third-party commissions, reduce waste, and build direct customer relationships.",
    heroVisual: {
      title: "F&B Operations Dashboard",
      subtitle: "Live Restaurant Analytics",
      mainStat: "40%",
      mainStatLabel: "Average Revenue Lift from Direct Digital Ordering",
      metrics: [
        { label: "Order Error Reduction", value: "85%" },
        { label: "Delivery Speed", value: "+30%" },
        { label: "Customer Retention", value: "+42%" },
        { label: "Inventory Waste", value: "−28%" },
      ],
    },
    trustStats: [
      { value: "60+", label: "F&B Platforms Delivered", icon: HiRocketLaunch },
      { value: "5M+", label: "Orders Processed", icon: HiChartBar },
      { value: "40%", label: "Avg. Revenue Lift", icon: HiCurrencyDollar },
      { value: "28%", label: "Avg. Inventory Waste Cut", icon: HiBolt },
    ],
    solutions: [
      { icon: HiShoppingCart, title: "Online Ordering & Delivery Platform", description: "White-label direct ordering web and mobile apps that bypass DoorDash and UberEats — keeping 15–25% commission per order in your pocket. Real-time kitchen integration included.", href: "/saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiCircleStack, title: "POS & Inventory Integration", description: "Bi-directional integrations with Toast, Square, Clover, and custom POS systems. Real-time inventory sync, low-stock alerts, and waste tracking across all locations.", href: "/erp-development", color: "from-blue-500 to-indigo-500" },
      { icon: HiDevicePhoneMobile, title: "Customer Loyalty & Rewards App", description: "Branded iOS and Android apps with points, rewards, push notifications, and customer behavior analytics — proven to increase visit frequency by 35%+.", href: "/staff-augmentation/hire-react-native-developers", color: "from-violet-500 to-purple-500" },
      { icon: HiCpuChip, title: "AI Menu & Demand Forecasting", description: "ML-powered demand forecasting, dynamic menu pricing, ingredient usage prediction, and waste reduction algorithms trained on your historical POS data.", href: "/ai-development/ai-workflow-automation", color: "from-orange-500 to-amber-500" },
      { icon: HiComputerDesktop, title: "Kitchen Display System (KDS)", description: "Custom KDS with real-time order routing from all channels (online, in-store, delivery), preparation timers, and front-of-house display management.", href: "/software-development", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBarSquare, title: "Multi-Location Operations Dashboard", description: "Centralized command center for chains and franchises — unified sales, labour, inventory, and guest review data across all locations in a single real-time dashboard.", href: "/erp-development/custom-erp-solutions", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiCurrencyDollar, title: "Third-Party Commission Drain", description: "Paying 15–25% commissions to DoorDash, Uber Eats, and Grubhub on every order erodes margins to near zero. Restaurants lose the customer data too — making retention impossible without owning the ordering channel." },
      { icon: HiCircleStack, title: "Inventory Waste and Shrinkage", description: "Without real-time inventory visibility, over-ordering is the norm. Industry data shows food waste averaging 4–10% of revenue — a direct profit leak preventable with proper inventory integration and forecasting." },
      { icon: HiComputerDesktop, title: "Disconnected Online and Offline Channels", description: "Orders coming in from 3 apps, the POS, and the website — all requiring manual reconciliation. Staff errors multiply, ticket times suffer, and no single source of truth exists for operations or reporting." },
      { icon: HiUsers, title: "Customer Retention in a Crowded Market", description: "No first-party customer data means no loyalty. Guests who order via third-party apps are the platform's customers — not yours. Without a direct relationship, churn is structural and impossible to address." },
    ],
    techStack: [
      { label: "React Native", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "Stripe", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "Firebase", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "Square / Clover API", color: "bg-slate-100 text-slate-700 border-slate-200" },
      { label: "Toast API", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Google Maps", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Twilio", color: "bg-red-100 text-red-700 border-red-200" },
      { label: "AWS", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "Redis", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
    ],
    relatedServices: [
      { title: "Custom ERP for Multi-Location Ops", description: "Centralize inventory, labour, purchasing, and reporting across all your restaurant locations and brands.", href: "/erp-development", tag: "ERP Development" },
      { title: "SaaS Platform Development", description: "Build white-label ordering and loyalty SaaS that you can license to other F&B brands as a secondary revenue stream.", href: "/saas-development", tag: "SaaS Development" },
      { title: "AI Workflow Automation", description: "Automate demand forecasting, prep scheduling, and waste reduction with AI pipelines trained on your POS data.", href: "/ai-development/ai-workflow-automation", tag: "AI Development" },
    ],
    faqs: [
      { q: "Can you integrate with our existing POS (Toast, Square, Clover)?", a: "Yes. We have integration experience with Toast, Square, Clover, Oracle MICROS, Lightspeed, and Revel. Integration complexity varies by POS — we map API capabilities during discovery and build bi-directional sync for menus, orders, and inventory." },
      { q: "How do we reduce DoorDash and UberEats commissions?", a: "We build you a branded ordering platform (web + app) with SEO, loyalty incentives, and direct marketing to shift order volume from third-party channels. Most clients recover the development cost in 3–6 months from commission savings alone on their existing order volume." },
      { q: "How long does it take to build a custom ordering app?", a: "A MVP ordering app with menu management, cart, checkout, and order tracking typically takes 8–12 weeks. A full platform with loyalty, KDS integration, multi-location support, and marketing tools is a 4–5 month engagement." },
      { q: "Can you build a loyalty and rewards program?", a: "Yes. We build points-based and tier-based loyalty systems with push notification campaigns, birthday rewards, referral programs, and A/B testing for promotions. Loyalty data feeds directly into your analytics dashboard." },
      { q: "Do you support multi-location and franchise operations?", a: "Yes. Our systems support centralized menu management with location-level overrides, consolidated reporting, franchise royalty tracking, and role-based access for operators, franchisees, and corporate staff." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "60+", label: "F&B platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "F&B technology specialists on every call",
      "ROI estimate based on your current order volume",
    ],
    floatingButtonLabel: "Book F&B Consultation",
  },

  /* ── Finance ───────────────────────────────────────────────────────────── */
  "finance": {
    slug: "finance",
    label: "Finance",
    badgeText: "Fintech Development Specialists",
    badgeIcon: HiBanknotes,
    headline: "Custom Fintech & Financial Software Development",
    subheadline: "Payment platforms, banking dashboards, lending portals, and compliance-grade financial software built for banks, credit unions, fintechs, and investment firms — engineered for SOC 2, PCI DSS, and AML compliance from the first line of code.",
    heroVisual: {
      title: "Fintech Operations Dashboard",
      subtitle: "Live Transaction Monitoring",
      mainStat: "99.99%",
      mainStatLabel: "Transaction Uptime SLA",
      metrics: [
        { label: "KYC Onboarding Time", value: "−70%" },
        { label: "Fraud Detection Rate", value: "97%" },
        { label: "Compliance Coverage", value: "100%" },
        { label: "Transaction Volume", value: "$2B+" },
      ],
    },
    trustStats: [
      { value: "40+", label: "Fintech Platforms Built", icon: HiRocketLaunch },
      { value: "$2B+", label: "Transaction Volume Handled", icon: HiCurrencyDollar },
      { value: "99.99%", label: "Uptime SLA", icon: HiBolt },
      { value: "SOC 2", label: "Compliant Architecture", icon: HiShieldCheck },
    ],
    solutions: [
      { icon: HiCloud, title: "Payment Processing Platform", description: "Custom payment gateways, multi-currency processing, split payments, and reconciliation dashboards — integrated with Stripe, Plaid, Adyen, and direct ACH/SEPA rails.", href: "/saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiComputerDesktop, title: "Banking & Neobank Dashboard", description: "Modern core banking interfaces, account management portals, and mobile banking apps built for neobanks, credit unions, and BaaS providers seeking to move beyond legacy UI.", href: "/erp-development/custom-erp-solutions", color: "from-blue-500 to-indigo-500" },
      { icon: HiShieldCheck, title: "KYC / AML Compliance Engine", description: "AI-powered identity verification, document OCR, sanctions screening, transaction monitoring, and SAR filing workflows — designed to pass regulatory audits from day one.", href: "/ai-development", color: "from-violet-500 to-purple-500" },
      { icon: HiChartBar, title: "Investment & Portfolio Platform", description: "Real-time portfolio tracking, robo-advisory algorithms, performance reporting, and client-facing dashboards for wealth management firms, RIAs, and investment platforms.", href: "/saas-development/multi-tenant-saas-development", color: "from-orange-500 to-amber-500" },
      { icon: HiDocumentText, title: "Loan Origination System", description: "End-to-end digital lending platforms covering application, underwriting, document collection, credit decisioning, disbursement, and repayment tracking with bureau API integration.", href: "/erp-development", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBarSquare, title: "Financial Analytics & BI Dashboard", description: "Real-time financial dashboards, regulatory reporting automation, and AI-powered anomaly detection for finance teams that need to move beyond spreadsheets.", href: "/ai-development/ai-chatbot-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiCircleStack, title: "Legacy Core System Debt", description: "Core banking systems and payment infrastructure built in the 1990s — requiring costly middleware just to integrate with APIs, mobile apps, or modern analytics stacks. Every modernization project carries risk of cascading failures." },
      { icon: HiShieldCheck, title: "Multi-Layer Regulatory Burden", description: "Navigating SOC 2, PCI DSS, AML, BSA, GDPR, and state-level requirements simultaneously — each with distinct audit trail, data residency, and access control mandates that pre-date cloud architecture." },
      { icon: HiBolt, title: "Real-Time Fraud Detection Gaps", description: "Rule-based fraud systems generating 20–40% false positive rates — blocking legitimate customers while still missing sophisticated fraud patterns that adaptive ML models catch in milliseconds." },
      { icon: HiUsers, title: "Onboarding Friction and Drop-Off", description: "KYC processes requiring 5–7 days and multiple manual touchpoints are losing customers to competitors who complete identity verification in under 3 minutes. Every day of onboarding friction costs measurable revenue." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "Python", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "AWS / GCP", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "Stripe / Plaid", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "KYC APIs (Jumio/Onfido)", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Redis", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "Elasticsearch", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
      { label: "PCI-DSS Compliant Infra", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "Insurance Software Development", description: "Compliance-grade portals, policy management systems, and claims automation for insurance and financial institutions.", href: "/insurance-software-development", tag: "Insurance Software" },
      { title: "AI Development", description: "Fraud detection models, credit risk scoring, and automated compliance checks powered by production-grade ML pipelines.", href: "/ai-development", tag: "AI Development" },
      { title: "SaaS Product Development", description: "Build multi-tenant fintech SaaS platforms with usage-based billing, white-labeling, and regulatory compliance built in.", href: "/saas-development", tag: "SaaS Development" },
    ],
    faqs: [
      { q: "How do you handle PCI DSS compliance for payment systems?", a: "Our payment integrations use Stripe or other Level-1 PCI compliant processors as the primary cardholder data vault — meaning card data never touches our infrastructure directly. For custom acquiring or vault needs, we architect systems to SAQ-D scope with tokenization, encryption at rest, and network segmentation audit-ready." },
      { q: "Can you integrate with core banking systems (Temenos, FIS, Fiserv)?", a: "Yes. We have integration experience with Temenos, FIS, Fiserv, nCino, and custom legacy core systems via REST, SOAP, ISO 20022, and file-based APIs. We map integration complexity during discovery and design graceful degradation for unreliable legacy APIs." },
      { q: "How long does it take to build a fintech platform?", a: "A focused module — KYC flow, loan origination, or payment portal — typically takes 8–16 weeks. A full fintech platform with core integrations, compliance workflows, and mobile apps is a 5–12 month engagement depending on regulatory scope." },
      { q: "How do you approach AML and transaction monitoring?", a: "We implement risk-scoring rule engines with configurable thresholds, integrate with third-party AML screening services (Refinitiv, ComplyAdvantage), and build SAR workflow automation. ML anomaly detection layers are added for high-volume clients. All workflows produce the audit trails required for FinCEN and BSA reporting." },
      { q: "What's the cost range for fintech software development?", a: "Scoped modules start from $60K–$100K (KYC flow, payment portal). Full platforms range from $200K–$800K+ depending on regulatory complexity, integration requirements, and feature scope. You receive a fixed-price estimate after the free technical discovery session." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "40+", label: "Fintech platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "Compliance engineers on every call",
      "SOC 2 & PCI-DSS architecture review",
    ],
    floatingButtonLabel: "Book Fintech Consultation",
  },

  /* ── Retail & eCommerce ────────────────────────────────────────────────── */
  "retail-ecommerce": {
    slug: "retail-ecommerce",
    label: "Retail & eCommerce",
    badgeText: "Retail & Commerce Specialists",
    badgeIcon: HiShoppingCart,
    headline: "Custom eCommerce & Retail Software Development",
    subheadline: "From headless commerce platforms and inventory management to customer analytics and B2B portals — we build omnichannel retail systems that drive conversion, reduce operational complexity, and scale with your catalogue.",
    heroVisual: {
      title: "Commerce Operations Dashboard",
      subtitle: "Live Retail Analytics",
      mainStat: "35%",
      mainStatLabel: "Average Conversion Rate Uplift",
      metrics: [
        { label: "Cart Abandonment", value: "−40%" },
        { label: "Order Processing", value: "3× Faster" },
        { label: "Inventory Accuracy", value: "99.2%" },
        { label: "Customer LTV", value: "+55%" },
      ],
    },
    trustStats: [
      { value: "70+", label: "Retail & eCommerce Projects", icon: HiRocketLaunch },
      { value: "35%", label: "Avg. Conversion Rate Uplift", icon: HiChartBar },
      { value: "$500M+", label: "GMV Managed on Our Platforms", icon: HiCurrencyDollar },
      { value: "99.2%", label: "Inventory Accuracy", icon: HiShieldCheck },
    ],
    solutions: [
      { icon: HiComputerDesktop, title: "Headless Commerce Platform", description: "API-first commerce infrastructure decoupled from the frontend — enabling personalized storefronts, mobile apps, kiosks, and IoT touchpoints from a single product/inventory layer.", href: "/saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiCircleStack, title: "Inventory & Order Management", description: "Real-time inventory across warehouses, stores, and 3PLs — with automated reorder triggers, multi-location allocation, and returns management built in.", href: "/erp-development/inventory-management-system", color: "from-blue-500 to-indigo-500" },
      { icon: HiCpuChip, title: "Customer Analytics & Personalization", description: "ML-powered recommendation engines, segmentation tools, and real-time personalization APIs that serve the right product to the right customer at every touchpoint.", href: "/ai-development", color: "from-violet-500 to-purple-500" },
      { icon: HiServerStack, title: "B2B Commerce Portal", description: "Trade portals with customer-specific pricing, bulk ordering, approval workflows, credit terms, and self-service account management — purpose-built for wholesale and distributor relationships.", href: "/saas-development/b2b-saas-development", color: "from-orange-500 to-amber-500" },
      { icon: HiStar, title: "Loyalty & Subscription Management", description: "Points programs, tiered memberships, subscription boxes, and renewal automation with analytics dashboards tracking cohort retention and LTV by acquisition channel.", href: "/saas-development/subscription-platform-development", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBarSquare, title: "POS & Omnichannel Integration", description: "Unified commerce that syncs orders, inventory, and customer data across online, in-store, marketplace, and social selling channels in real time.", href: "/erp-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiComputerDesktop, title: "Fragmented Online and Offline Channels", description: "Customers expect a seamless experience across your website, app, store, and marketplaces — but disconnected systems mean separate inventory, conflicting promotions, and split loyalty data. Every channel operating in isolation loses sales." },
      { icon: HiCircleStack, title: "Inventory Complexity Across Locations", description: "Managing stock across multiple warehouses, stores, and 3PL providers without real-time sync leads to overselling, stockouts, and write-offs. Manual reconciliation consumes hours daily and is always one step behind." },
      { icon: HiUsers, title: "Losing Ground to Pure-Play Digitals", description: "Amazon, ASOS, and digitally native brands are setting expectations your legacy platform can't match — 1-click checkout, real-time delivery tracking, personalized feeds, and instant returns. The UX gap grows every quarter." },
      { icon: HiDocumentText, title: "Returns Management Costs", description: "Returns rates of 20–40% in apparel and electronics create reverse logistics costs that erode margins. Without automated returns workflows and analytics, root causes go unaddressed and the problem compounds." },
    ],
    techStack: [
      { label: "Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "Elasticsearch", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "Stripe / Adyen", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Shopify / BigCommerce API", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "AWS CloudFront", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "Algolia", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
      { label: "React Native", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "Custom ERP & Inventory Management", description: "Unify procurement, warehousing, order management, and supplier relationships in one platform built for retail scale.", href: "/erp-development", tag: "ERP Development" },
      { title: "AI Personalization & Recommendations", description: "Deploy ML recommendation engines and predictive analytics to increase average order value and reduce churn.", href: "/ai-development", tag: "AI Development" },
      { title: "B2B SaaS Development", description: "Build trade portals and wholesale platforms that give your B2B buyers a digital-first self-service experience.", href: "/saas-development/b2b-saas-development", tag: "SaaS Development" },
    ],
    faqs: [
      { q: "Should we build custom or use Shopify/WooCommerce?", a: "For most brands under $10M GMV with standard product catalogues, Shopify or a headless Shopify build is faster and more cost-effective. We recommend custom when you have complex B2B pricing, non-standard checkout flows, product configurators, high-volume catalog (100K+ SKUs), or need tight ERP integration. We'll give you an honest recommendation in the discovery session." },
      { q: "How do you handle high-traffic events like Black Friday?", a: "We architect commerce platforms with auto-scaling groups, CDN edge caching, Redis session management, and load-tested infrastructure. Our builds are load-tested to 10× projected peak traffic before launch. We've delivered platforms that handled 50K concurrent users without degradation." },
      { q: "Can you integrate with our existing ERP or warehouse management system?", a: "Yes. We've integrated with SAP, NetSuite, Microsoft Dynamics, and custom WMS systems. Integration patterns depend on the ERP's API capabilities — REST, SOAP, EDI, and file-based imports all supported." },
      { q: "How long does it take to build a headless commerce platform?", a: "A focused headless storefront migrating from Shopify typically takes 8–14 weeks. A full platform with inventory management, OMS, B2B portal, and mobile app is a 4–6 month engagement." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "70+", label: "Retail projects" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "Commerce engineers on every call",
      "Honest build vs. configure recommendation",
    ],
    floatingButtonLabel: "Book Commerce Consultation",
  },

  /* ── Real Estate ───────────────────────────────────────────────────────── */
  "real-estate": {
    slug: "real-estate",
    label: "Real Estate",
    badgeText: "PropTech Specialists",
    badgeIcon: HiHome,
    headline: "Custom Real Estate Software & PropTech Development",
    subheadline: "Property portals, CRM systems, lease management platforms, and investment analytics tools built for real estate agencies, property managers, developers, and PropTech startups — engineered to accelerate deals and automate tenant operations.",
    heroVisual: {
      title: "PropTech Operations Dashboard",
      subtitle: "Live Property Analytics",
      mainStat: "3×",
      mainStatLabel: "Faster Deal Closure Reported by Clients",
      metrics: [
        { label: "Lead Response Time", value: "−80%" },
        { label: "Lease Renewals", value: "+35%" },
        { label: "Listings Published/Day", value: "10×" },
        { label: "Maintenance Resolution", value: "+60%" },
      ],
    },
    trustStats: [
      { value: "40+", label: "PropTech Platforms Built", icon: HiRocketLaunch },
      { value: "500K+", label: "Property Listings Managed", icon: HiMapPin },
      { value: "3×", label: "Faster Deal Closure", icon: HiBolt },
      { value: "35%", label: "Higher Lease Renewal Rate", icon: HiStar },
    ],
    solutions: [
      { icon: HiMapPin, title: "Property Listing & Search Portal", description: "MLS-integrated listing portals with map search, advanced filters, virtual tours, and lead capture — built to rank on Google and convert organic traffic to qualified inquiries.", href: "/saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiUserGroup, title: "Real Estate CRM", description: "Pipeline management, automated lead nurturing, deal tracking, commission calculation, and agent performance analytics — replacing spreadsheets and generic CRMs with domain-specific intelligence.", href: "/erp-development/custom-erp-solutions", color: "from-blue-500 to-indigo-500" },
      { icon: HiDocumentText, title: "Lease & Property Management System", description: "End-to-end tenant lifecycle — applications, background checks, lease signing, rent collection, maintenance requests, and renewal automation — in one compliant platform.", href: "/erp-development", color: "from-violet-500 to-purple-500" },
      { icon: HiChartBar, title: "Investment Analytics Dashboard", description: "Cap rate calculators, cash flow projections, portfolio performance tracking, and market comparable analysis for real estate investors and fund managers.", href: "/ai-development", color: "from-orange-500 to-amber-500" },
      { icon: HiComputerDesktop, title: "Virtual Tour & Digital Document Platform", description: "3D virtual tour integration, e-signature for leases and purchase agreements, document management, and digital closing workflows that eliminate paper from the transaction.", href: "/saas-development/multi-tenant-saas-development", color: "from-rose-500 to-pink-500" },
      { icon: HiDevicePhoneMobile, title: "Tenant & Landlord Mobile App", description: "Self-service apps for rent payment, maintenance requests, lease renewal, move-in/out checklists, and in-app messaging — dramatically reducing property manager inbound call volume.", href: "/staff-augmentation/hire-react-native-developers", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiUsers, title: "Lead Leakage and CRM Gaps", description: "Leads coming in from Zillow, Realtor.com, the website, and social — with no unified inbox or automated follow-up. Studies show 35–50% of leads go uncontacted within the critical 5-minute response window, and most are never re-engaged." },
      { icon: HiDocumentText, title: "Manual Lease and Compliance Documentation", description: "Printing, scanning, and emailing lease agreements across parties — with no audit trail. Missed clauses, outdated addendums, and state-specific compliance errors create legal exposure on every transaction." },
      { icon: HiCircleStack, title: "Fragmented Property Data", description: "MLS feeds, internal listing databases, Zillow/CoStar data, and internal CRM existing in separate silos. Accurate portfolio reporting requires pulling from 5+ sources and manually reconciling discrepancies." },
      { icon: HiWrenchScrewdriver, title: "Slow Maintenance Resolution", description: "Tenants submitting requests via text, email, and phone calls — with no unified tracking. Average maintenance resolution times of 7–14 days drive lease non-renewals and online review damage that costs more than the repairs." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "Google Maps API", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "Twilio", color: "bg-red-100 text-red-700 border-red-200" },
      { label: "DocuSign", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "Stripe", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "React Native", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "AWS", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "MLS / RETS API", color: "bg-slate-100 text-slate-700 border-slate-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
    ],
    relatedServices: [
      { title: "Custom ERP & Operations Management", description: "Centralize property management, lease tracking, maintenance operations, and financial reporting across your entire portfolio.", href: "/erp-development", tag: "ERP Development" },
      { title: "SaaS Product Development", description: "Build PropTech SaaS platforms that serve multiple agencies, brokerages, or property managers as a scalable business.", href: "/saas-development", tag: "SaaS Development" },
      { title: "Hire Dedicated PropTech Engineers", description: "Augment your team with engineers who have prior real estate platform experience, available in 72 hours.", href: "/staff-augmentation", tag: "Staff Augmentation" },
    ],
    faqs: [
      { q: "Can you integrate with MLS / IDX feeds?", a: "Yes. We have experience integrating with RETS, RESO Web API, and Spark API for MLS data. We also integrate with aggregators like Bridge Interactive and ListHub. Data sync frequency, field mapping, and listing deduplication logic are all configurable." },
      { q: "How do you handle state-specific lease compliance?", a: "We design lease templates and clause libraries that are jurisdiction-aware, with required disclosures populated dynamically based on property state and property type. We work alongside your legal counsel to validate state-specific requirements before the system is deployed." },
      { q: "Can you build a PropTech SaaS that serves multiple agencies?", a: "Yes — multi-tenant architecture is a core competency. We've built PropTech SaaS products that serve hundreds of agencies from a single platform with isolated data, custom branding per tenant, and tiered feature plans." },
      { q: "How long to build a real estate CRM or property portal?", a: "A CRM with pipeline management, lead automation, and agent reporting takes 8–12 weeks. A full property listing portal with MLS integration, tenant portal, and mobile app is a 4–6 month engagement." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "40+", label: "PropTech platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "PropTech engineers on every call",
      "MLS integration scoping included",
    ],
    floatingButtonLabel: "Book PropTech Consultation",
  },

  /* ── Healthcare ────────────────────────────────────────────────────────── */
  "healthcare": {
    slug: "healthcare",
    label: "Healthcare",
    badgeText: "HealthTech Specialists",
    badgeIcon: HiHeart,
    headline: "Custom Healthcare Software & HealthTech Development",
    subheadline: "Patient portals, electronic health records, telemedicine platforms, and HIPAA-compliant apps built for hospitals, clinics, telehealth providers, and healthcare SaaS companies — engineered for security, interoperability, and patient experience.",
    heroVisual: {
      title: "HealthTech Operations Dashboard",
      subtitle: "Live Clinical Analytics",
      mainStat: "40%",
      mainStatLabel: "Average Reduction in Administrative Workload",
      metrics: [
        { label: "Patient Satisfaction", value: "94%" },
        { label: "Claims First-Pass Rate", value: "89%" },
        { label: "Appointment No-Shows", value: "−35%" },
        { label: "HIPAA Compliance", value: "100%" },
      ],
    },
    trustStats: [
      { value: "45+", label: "Healthcare Platforms Delivered", icon: HiRocketLaunch },
      { value: "40%", label: "Admin Workload Reduction", icon: HiClock },
      { value: "HIPAA", label: "Compliant Architecture", icon: HiShieldCheck },
      { value: "94%", label: "Patient Satisfaction Score", icon: HiStar },
    ],
    solutions: [
      { icon: HiDocumentText, title: "Patient Portal & EHR System", description: "Secure patient portals with health record access, appointment scheduling, prescription refills, and secure messaging — built on HL7 FHIR for interoperability with major EHR systems.", href: "/erp-development/custom-erp-solutions", color: "from-teal-500 to-cyan-500" },
      { icon: HiComputerDesktop, title: "Telemedicine Platform", description: "HIPAA-compliant video consultation platforms with virtual waiting rooms, e-prescribing, care notes, and EHR integration — for telehealth startups and health systems expanding remote care.", href: "/saas-development/multi-tenant-saas-development", color: "from-blue-500 to-indigo-500" },
      { icon: HiDevicePhoneMobile, title: "Healthcare Mobile App", description: "Patient-facing iOS and Android apps for appointment booking, chronic disease management, medication reminders, remote monitoring integration, and care team messaging.", href: "/staff-augmentation/hire-react-native-developers", color: "from-violet-500 to-purple-500" },
      { icon: HiCpuChip, title: "AI Clinical Decision Support", description: "ML-powered diagnostic assistance, risk stratification, care gap identification, and prior authorization automation — trained on clinical data to reduce cognitive load and improve outcomes.", href: "/ai-development", color: "from-orange-500 to-amber-500" },
      { icon: HiCircleStack, title: "Medical Billing & Revenue Cycle", description: "Automated charge capture, claims scrubbing, denial management, and payment posting workflows that improve first-pass claim rates and reduce A/R days without adding billing staff.", href: "/erp-development", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBarSquare, title: "Healthcare Analytics Dashboard", description: "Population health analytics, operational KPIs, quality measures tracking, and payer performance reporting that give leadership actionable data to drive clinical and financial decisions.", href: "/ai-development/ai-chatbot-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiShieldCheck, title: "HIPAA Compliance Complexity", description: "Every vendor, system, and employee access point is a potential HIPAA liability. Business Associate Agreements, audit logs, access controls, encryption at rest and in transit, and breach notification procedures add layers of complexity most development teams aren't equipped to handle correctly." },
      { icon: HiCircleStack, title: "Legacy EHR Integration Barriers", description: "Epic, Cerner, and Allscripts have complex, often restricted API access that requires certified integration partners and lengthy approval processes. Data fragmented across these systems blocks care coordination and prevents patient-facing innovation." },
      { icon: HiCalendarDays, title: "Patient No-Shows and Engagement Gaps", description: "No-show rates of 15–30% cost US healthcare providers $150 billion annually in lost revenue. Without automated reminders, easy rescheduling, and proactive outreach, practices absorb this loss as an unavoidable cost of care." },
      { icon: HiDocumentText, title: "Manual Billing and High Denial Rates", description: "Average claims denial rates of 5–10% require costly manual rework. Without automated eligibility verification, code validation, and denial root cause analytics, billing teams fight the same errors repeatedly while A/R days climb." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "HL7 / FHIR R4", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "PostgreSQL", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "AWS HIPAA BAA", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "Twilio Video", color: "bg-red-100 text-red-700 border-red-200" },
      { label: "React Native", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "Python / ML", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "SMART on FHIR", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "Custom ERP & Operations Management", description: "Patient data management, care coordination workflows, and healthcare operations platforms that comply with HIPAA from the ground up.", href: "/erp-development", tag: "ERP Development" },
      { title: "AI Development", description: "Clinical decision support, predictive risk models, and automated prior authorization powered by production-grade machine learning.", href: "/ai-development", tag: "AI Development" },
      { title: "Hire HealthTech Engineers", description: "Dedicated engineers with HIPAA and FHIR experience, available to join your team in 72 hours.", href: "/staff-augmentation", tag: "Staff Augmentation" },
    ],
    faqs: [
      { q: "How do you ensure HIPAA compliance throughout development?", a: "We sign a Business Associate Agreement (BAA) before any PHI is involved. We architect systems with encryption at rest (AES-256) and in transit (TLS 1.3), role-based access controls, audit log immutability, and automated access review workflows. We use AWS or GCP with HIPAA-eligible services and BAA coverage." },
      { q: "Can you integrate with Epic, Cerner, or Athenahealth?", a: "Yes. We integrate via HL7 FHIR R4 APIs where available (Epic MyChart, Cerner Millennium), and via HL7 v2.x messaging for legacy systems. Epic SMART on FHIR app certification support is included. Integration scope and timeline depend on the specific EHR and the data exchange requirements." },
      { q: "How long does it take to build a telemedicine platform?", a: "A focused telemedicine MVP — video consultation, appointment booking, and secure messaging — typically takes 10–14 weeks. A full platform with EHR integration, e-prescribing, billing, and mobile apps is a 4–7 month engagement." },
      { q: "What experience do your engineers have with FHIR and healthcare interoperability?", a: "Our HealthTech team has direct experience with FHIR R4 API development, HL7 v2.x message parsing, CDA document handling, and SMART on FHIR application development. We've completed Epic App Orchard submissions and Cerner Code integrations." },
      { q: "What does healthcare software development cost?", a: "A focused module (patient portal, telemedicine MVP) starts at $50K–$100K. A full healthcare platform with EHR integration, billing, mobile, and AI features ranges from $200K–$600K+. You receive a detailed estimate with milestone breakdown after the free discovery session." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "45+", label: "HealthTech platforms" },
    ],
    trustItems: [
      "NDA and BAA signed before any PHI discussion",
      "HIPAA-certified engineers on every call",
      "FHIR integration scoping included",
    ],
    floatingButtonLabel: "Book HealthTech Consultation",
  },

  /* ── Transport & Logistics ─────────────────────────────────────────────── */
  "transport-logistics": {
    slug: "transport-logistics",
    label: "Transport & Logistics",
    badgeText: "Logistics Technology Experts",
    badgeIcon: HiTruck,
    headline: "Custom Transport & Logistics Software Development",
    subheadline: "Fleet management systems, route optimization, real-time shipment tracking, and warehouse management platforms built for 3PLs, freight brokers, last-mile carriers, and supply chain operators — engineered to cut cost per delivery and maximize fleet visibility.",
    heroVisual: {
      title: "Logistics Operations Dashboard",
      subtitle: "Live Fleet Analytics",
      mainStat: "28%",
      mainStatLabel: "Average Cost-Per-Delivery Reduction",
      metrics: [
        { label: "Route Efficiency", value: "+35%" },
        { label: "On-Time Delivery", value: "97%" },
        { label: "Fleet Utilization", value: "+40%" },
        { label: "Fuel Cost", value: "−22%" },
      ],
    },
    trustStats: [
      { value: "35+", label: "Logistics Platforms Built", icon: HiRocketLaunch },
      { value: "50K+", label: "Vehicles Tracked Live", icon: HiTruck },
      { value: "28%", label: "Avg. Cost-Per-Delivery Cut", icon: HiCurrencyDollar },
      { value: "97%", label: "On-Time Delivery Rate", icon: HiBolt },
    ],
    solutions: [
      { icon: HiTruck, title: "Fleet Management System", description: "Real-time vehicle tracking, maintenance scheduling, driver management, compliance reporting, and telematics integration — giving dispatchers complete fleet visibility from a single dashboard.", href: "/erp-development/custom-erp-solutions", color: "from-teal-500 to-cyan-500" },
      { icon: HiMapPin, title: "Route Optimization & Dispatch", description: "AI-powered multi-stop route optimization that reduces drive time by 15–25%, with dynamic re-routing for traffic, delays, and priority order changes — dispatched automatically to driver apps.", href: "/ai-development/ai-workflow-automation", color: "from-blue-500 to-indigo-500" },
      { icon: HiComputerDesktop, title: "Real-Time Shipment Tracking", description: "Customer-facing tracking portals and carrier API aggregation giving shippers and end customers real-time visibility across all carriers and modes — with proactive exception alerts.", href: "/saas-development", color: "from-violet-500 to-purple-500" },
      { icon: HiCircleStack, title: "Warehouse Management System", description: "Inbound, putaway, pick-pack-ship, and outbound workflows with barcode/RFID integration, slotting optimization, and labour management — reducing pick errors and increasing throughput.", href: "/erp-development/warehouse-management-system", color: "from-orange-500 to-amber-500" },
      { icon: HiDevicePhoneMobile, title: "Driver Mobile App", description: "iOS and Android driver apps with turn-by-turn navigation, POD capture, electronic signature, DVIR, HOS logging, and real-time communication with dispatch.", href: "/staff-augmentation/hire-react-native-developers", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBarSquare, title: "Supply Chain Analytics Dashboard", description: "End-to-end supply chain visibility with carrier performance scorecards, lane cost analytics, inventory in-transit tracking, and exception management dashboards.", href: "/ai-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiComputerDesktop, title: "Shipment Visibility Gaps", description: "Multi-carrier operations with no unified tracking view — customers calling for updates, operations teams screen-scraping 10 carrier portals, and exceptions discovered hours after they become service failures." },
      { icon: HiMapPin, title: "Inefficient Manual Dispatch and Routing", description: "Dispatchers manually building routes based on experience — leaving 15–25% efficiency on the table. Without optimization algorithms, fuel waste, overtime, and missed time windows compound daily across the fleet." },
      { icon: HiDocumentText, title: "ELD and HOS Compliance Risk", description: "FMCSA Hours of Service regulations carry fines of $16,000+ per violation. Paper logbooks, manual checks, and disconnected ELD systems leave carriers exposed to compliance risk with every load." },
      { icon: HiCircleStack, title: "Disconnected Warehouse and Transport Operations", description: "Warehouse management systems that don't talk to TMS create dock scheduling delays, carrier wait times, and inventory discrepancies. The gap between pick completion and truck departure is a daily source of SLA failures." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "Google Maps / HERE API", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "GPS / Telematics APIs", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "React Native", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "AWS IoT Core", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Python / ML", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
      { label: "EDI / FTP Integration", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "Warehouse Management System", description: "Custom WMS with pick-pack-ship workflows, RFID integration, and yard management built for high-throughput operations.", href: "/erp-development/warehouse-management-system", tag: "ERP Development" },
      { title: "AI Workflow Automation", description: "ML-powered route optimization, predictive maintenance models, and demand forecasting for supply chain operations.", href: "/ai-development/ai-workflow-automation", tag: "AI Development" },
      { title: "SaaS Platform Development", description: "Build multi-carrier visibility platforms and logistics SaaS products that serve shippers, brokers, and 3PLs.", href: "/saas-development", tag: "SaaS Development" },
    ],
    faqs: [
      { q: "Can you integrate with our existing TMS (McLeod, TMW, Samsara)?", a: "Yes. We have integration experience with McLeod, TMW Suite, Samsara, KeepTruckin/Motive, and custom TMS systems via REST, SOAP, and EDI X12. Integration scope and data mapping are defined during discovery." },
      { q: "How does the route optimization algorithm work?", a: "We implement Constraint Programming (CP-SAT) and Vehicle Routing Problem (VRP) solvers, with ML models layered for real-world factors like traffic patterns, driver preferences, and customer time windows. The algorithm improves with every completed route through feedback loops." },
      { q: "Can you build ELD-compliant driver apps?", a: "Yes. We build FMCSA-compliant Hours of Service (HOS) logging, DVIR (Driver Vehicle Inspection Report), and electronic logbook features integrated with hardware ELD devices via Bluetooth and cellular APIs." },
      { q: "How long to build a fleet management or logistics platform?", a: "A focused fleet tracking and dispatch system takes 10–16 weeks. A full TMS with optimization, WMS integration, driver app, and customer portal is a 5–8 month engagement." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "35+", label: "Logistics platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "Logistics domain engineers on every call",
      "Route optimization benchmarking included",
    ],
    floatingButtonLabel: "Book Logistics Consultation",
  },

  /* ── Travel & Hospitality ──────────────────────────────────────────────── */
  "travel-hospitality": {
    slug: "travel-hospitality",
    label: "Travel & Hospitality",
    badgeText: "Travel Tech Specialists",
    badgeIcon: HiGlobeAlt,
    headline: "Custom Travel & Hospitality Software Development",
    subheadline: "Booking engines, property management systems, guest experience apps, and revenue management platforms built for hotels, OTAs, tour operators, and travel tech startups — engineered to reduce OTA dependency, maximise direct bookings, and delight guests at every touchpoint.",
    heroVisual: {
      title: "Hospitality Operations Dashboard",
      subtitle: "Live Booking Analytics",
      mainStat: "25%",
      mainStatLabel: "Average Direct Booking Rate Increase",
      metrics: [
        { label: "Booking Abandonment", value: "−38%" },
        { label: "RevPAR Improvement", value: "+22%" },
        { label: "Guest NPS", value: "+31 pts" },
        { label: "Channels Connected", value: "12+" },
      ],
    },
    trustStats: [
      { value: "30+", label: "Travel & Hospitality Platforms", icon: HiRocketLaunch },
      { value: "25%", label: "Avg. Direct Booking Lift", icon: HiChartBar },
      { value: "38%", label: "Fewer Abandoned Bookings", icon: HiBolt },
      { value: "12+", label: "Distribution Channels Connected", icon: HiGlobeAlt },
    ],
    solutions: [
      { icon: HiComputerDesktop, title: "Booking Engine & Reservation System", description: "High-converting direct booking websites with rate parity tools, upsell flows, multi-room booking, and real-time availability — integrated with your PMS and channel manager to stop OTA leakage.", href: "/saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiCircleStack, title: "Property Management System (PMS)", description: "Cloud-native PMS covering reservations, front desk, housekeeping, maintenance, and reporting — replacing legacy on-premise systems with a modern API-first architecture.", href: "/erp-development/custom-erp-solutions", color: "from-blue-500 to-indigo-500" },
      { icon: HiDevicePhoneMobile, title: "Guest Experience Mobile App", description: "Pre-arrival upsells, mobile check-in/check-out, digital room keys, in-app concierge, F&B ordering, and post-stay review requests — delivering the contactless experience modern guests expect.", href: "/staff-augmentation/hire-react-native-developers", color: "from-violet-500 to-purple-500" },
      { icon: HiCpuChip, title: "Revenue Management & Dynamic Pricing", description: "AI-driven pricing algorithms that analyse demand signals, competitor rates, and booking pace to optimise RevPAR in real time — replacing manual rate decisions with data-driven automation.", href: "/ai-development/ai-workflow-automation", color: "from-orange-500 to-amber-500" },
      { icon: HiCloud, title: "Channel Manager & OTA Integration", description: "Two-way XML/REST integrations with Booking.com, Expedia, Airbnb, GDS (Amadeus/Sabre), and 100+ OTAs — with real-time rate and availability sync to prevent overbooking and rate disparity.", href: "/saas-development/multi-tenant-saas-development", color: "from-rose-500 to-pink-500" },
      { icon: HiUserGroup, title: "Guest Loyalty & CRM", description: "Branded loyalty programs with points, tier benefits, and personalized communications — capturing the direct relationship with repeat guests that OTAs deliberately prevent.", href: "/saas-development/crm-saas-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiCurrencyDollar, title: "OTA Commission Dependency", description: "Paying 15–25% commission on every OTA-sourced booking — often for guests who would have booked direct if the booking experience was as smooth. Direct booking engines typically recover development cost within 6–12 months in commission savings alone." },
      { icon: HiCircleStack, title: "Fragmented Booking Data", description: "Reservations coming in from Booking.com, Expedia, GDS, direct web, and phone — each in different formats, with no unified guest record. Overbooking risk, duplicate profiles, and incomplete guest histories are structural problems without proper channel integration." },
      { icon: HiDevicePhoneMobile, title: "Poor Mobile Guest Experience", description: "85% of travelers research on mobile, and 45%+ complete bookings on mobile — yet most hotel websites are mobile-afterthoughts. Slow load times, awkward forms, and no mobile check-in lead to abandoned bookings and frustrated guests." },
      { icon: HiChartBar, title: "Manual Revenue Management", description: "Revenue managers setting rates manually in spreadsheets — unable to respond to real-time demand signals, competitor price changes, or last-minute availability. Dynamic pricing ML can lift RevPAR 8–18% with no added headcount." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "Stripe", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "Twilio", color: "bg-red-100 text-red-700 border-red-200" },
      { label: "Amadeus / Sabre API", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "Google Maps", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "React Native", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "AWS", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Channel Manager APIs", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "SaaS Platform Development", description: "Build multi-tenant hospitality SaaS products — booking engines, PMS, or channel managers — that serve multiple properties from one platform.", href: "/saas-development", tag: "SaaS Development" },
      { title: "AI Workflow Automation", description: "Deploy dynamic pricing models, demand forecasting, and guest personalization algorithms that optimise revenue in real time.", href: "/ai-development/ai-workflow-automation", tag: "AI Development" },
      { title: "Custom ERP Development", description: "Unified property operations, procurement, housekeeping management, and financial reporting for hotel groups and resorts.", href: "/erp-development", tag: "ERP Development" },
    ],
    faqs: [
      { q: "Can you integrate with our existing PMS (Opera, Mews, Cloudbeds)?", a: "Yes. We integrate with Opera (Oracle OHIP), Mews, Cloudbeds, Apaleo, and custom PMS systems via REST and XML APIs. Integration scope covers reservations, rate/availability sync, guest profile management, and folio data." },
      { q: "How long to build a direct booking engine?", a: "A high-converting direct booking website with PMS integration, rate management, and upsell flows typically takes 8–12 weeks. A full-suite hospitality platform with mobile app, channel manager, and revenue management takes 5–8 months." },
      { q: "How does your revenue management AI work?", a: "We train pricing models on your historical occupancy, ADR, and booking pace data alongside competitive rate feeds and event calendars. The model updates rates multiple times per day across all connected channels, with a management override dashboard for manual intervention." },
      { q: "Can you build a multi-property platform for a hotel group?", a: "Yes — multi-property and multi-brand architecture is a core strength. We build shared PMS infrastructure with property-level data isolation, consolidated corporate reporting, centralized loyalty programs, and independent property websites from a single backend." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "30+", label: "Hospitality platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "Travel tech engineers on every call",
      "OTA commission ROI modelling included",
    ],
    floatingButtonLabel: "Book Travel Tech Consultation",
  },

  /* ── Manufacturing ─────────────────────────────────────────────────────── */
  "manufacturing": {
    slug: "manufacturing",
    label: "Manufacturing",
    badgeText: "Industrial Software Experts",
    badgeIcon: HiWrenchScrewdriver,
    headline: "Custom Manufacturing Software & Industry 4.0 Development",
    subheadline: "Manufacturing execution systems, ERP, quality management, IoT integration, and production analytics platforms built for discrete and process manufacturers — engineered to increase OEE, reduce defects, and give operators real-time visibility across every line.",
    heroVisual: {
      title: "Manufacturing Operations Dashboard",
      subtitle: "Live Shop Floor Analytics",
      mainStat: "22%",
      mainStatLabel: "Average OEE Improvement",
      metrics: [
        { label: "Defect Rate", value: "−35%" },
        { label: "Machine Downtime", value: "−40%" },
        { label: "Production Throughput", value: "+28%" },
        { label: "Compliance Audits", value: "100% Pass" },
      ],
    },
    trustStats: [
      { value: "25+", label: "Manufacturing Platforms Built", icon: HiRocketLaunch },
      { value: "22%", label: "Avg. OEE Improvement", icon: HiBolt },
      { value: "35%", label: "Fewer Production Defects", icon: HiShieldCheck },
      { value: "I4.0", label: "Industry 4.0 Architecture", icon: HiCpuChip },
    ],
    solutions: [
      { icon: HiCircleStack, title: "Manufacturing Execution System (MES)", description: "Real-time shop floor control covering work order management, material tracking, labour booking, quality gates, and production reporting — replacing paper travelers and spreadsheets with live digital workflows.", href: "/erp-development/manufacturing-erp-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiChartBarSquare, title: "Custom ERP for Manufacturers", description: "Integrated manufacturing ERP covering production planning, BOM management, inventory, procurement, costing, and financial reporting — built around your processes rather than forcing your team into a generic template.", href: "/erp-development/custom-erp-solutions", color: "from-blue-500 to-indigo-500" },
      { icon: HiDocumentText, title: "Quality Management System (QMS)", description: "Digital quality workflows covering incoming inspection, in-process checks, nonconformance management, CAPA tracking, and audit management — with full AS9100/ISO 9001 traceability.", href: "/erp-development", color: "from-violet-500 to-purple-500" },
      { icon: HiCpuChip, title: "IoT & Shop Floor Integration", description: "Machine connectivity via OPC-UA, MQTT, and Modbus protocols — aggregating sensor data, cycle times, and machine states into real-time dashboards that drive predictive maintenance and OEE analytics.", href: "/ai-development/ai-workflow-automation", color: "from-orange-500 to-amber-500" },
      { icon: HiServerStack, title: "Production Planning & Scheduling", description: "Advanced Planning & Scheduling (APS) tools with constraint-based finite capacity scheduling, what-if scenario modelling, and integration with your ERP work order system.", href: "/erp-development/inventory-management-system", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBar, title: "Supply Chain Analytics", description: "Supplier performance scorecards, demand forecasting, inventory optimization, and supply risk dashboards that help purchasing and supply chain teams stay ahead of disruptions.", href: "/ai-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiComputerDesktop, title: "No Real-Time Shop Floor Visibility", description: "Production managers learning about quality escapes and machine stoppages hours after they happen — via phone calls or daily paper reports. Without real-time data from the floor, reactive firefighting is the operating mode." },
      { icon: HiDocumentText, title: "Manual Quality Control and Audit Trails", description: "Paper-based inspection records, manual nonconformance tickets, and disconnected CAPA tracking that fail ISO/AS9100 audits and create regulatory exposure. Every paper process is a data gap waiting to cause a customer complaint." },
      { icon: HiCircleStack, title: "Disconnected ERP, MES, and IoT Systems", description: "Enterprise ERP that doesn't receive real-time production data. MES that doesn't feed quality events upstream. IoT sensors generating streams of data that sit in silos. The system of record is perpetually out of sync with what's actually happening on the floor." },
      { icon: HiWrenchScrewdriver, title: "Unplanned Downtime from Reactive Maintenance", description: "Reactive maintenance strategies — fixing machines after they break — average 10× the cost of preventive maintenance and create unpredictable production gaps. Predictive maintenance using IoT sensor data and ML can reduce unplanned downtime by 30–50%." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "PostgreSQL / TimescaleDB", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "OPC-UA / MQTT", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "AWS IoT Core", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "Python / ML", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
      { label: "Grafana / Prometheus", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "REST / ERP APIs", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "Manufacturing ERP Development", description: "Custom ERP systems built for discrete and process manufacturers — BOM, production planning, quality, and financial reporting in one platform.", href: "/erp-development/manufacturing-erp-development", tag: "ERP Development" },
      { title: "AI & IoT Automation", description: "Predictive maintenance models, quality anomaly detection, and production yield optimization powered by shop floor sensor data.", href: "/ai-development/ai-workflow-automation", tag: "AI Development" },
      { title: "Hire Industrial Software Engineers", description: "Dedicated engineers with MES, ERP, and IoT integration experience for manufacturing environments, available in 72 hours.", href: "/staff-augmentation", tag: "Staff Augmentation" },
    ],
    faqs: [
      { q: "Can you integrate with our existing ERP (SAP, Oracle, Microsoft Dynamics)?", a: "Yes. We integrate with SAP S/4HANA, Oracle ERP Cloud, Microsoft Dynamics 365, Infor, and custom ERP systems via REST APIs, BAPI/RFC (SAP), and file-based interfaces. We map integration data flows and latency requirements during discovery." },
      { q: "How do you connect to shop floor machines and PLCs?", a: "We use OPC-UA, MQTT, and Modbus protocols for PLC and SCADA connectivity. For older equipment without network interfaces, we deploy edge computing gateways (Raspberry Pi or industrial PC) with protocol converters. Data is aggregated in real time to cloud dashboards." },
      { q: "What is OEE and how do your platforms improve it?", a: "OEE (Overall Equipment Effectiveness) measures Availability × Performance × Quality. Our platforms improve OEE by eliminating data collection delays (real-time IoT feeds), identifying quality patterns before they become defect clusters, and enabling operators to respond to downtime events within minutes rather than hours." },
      { q: "How long to build a manufacturing MES or ERP system?", a: "A focused MES module (work order management, production reporting) takes 12–16 weeks. A full manufacturing ERP with MES integration, QMS, and shop floor IoT connectivity is a 6–12 month engagement depending on production complexity." },
      { q: "Can your QMS support ISO 9001 / AS9100 / IATF 16949 audits?", a: "Yes. We design QMS workflows with the complete audit trail, document control, CAPA lifecycle, and management review report generation required for ISO 9001, AS9100, and IATF 16949 surveillance and recertification audits. Several clients have passed third-party audits within 6 months of going live on our platform." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "25+", label: "Manufacturing platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "Manufacturing domain engineers on every call",
      "OEE baseline assessment included",
    ],
    floatingButtonLabel: "Book Manufacturing Consultation",
  },

  /* ── Media & Entertainment ─────────────────────────────────────────────── */
  "media-entertainment": {
    slug: "media-entertainment",
    label: "Media & Entertainment",
    badgeText: "Digital Media Specialists",
    badgeIcon: HiFilm,
    headline: "Custom Media & Entertainment Software Development",
    subheadline: "Streaming platforms, content management systems, subscription monetization, and creator tools built for media companies, broadcasters, OTT providers, and digital content businesses — engineered for global scale, personalisation, and maximum subscription revenue.",
    heroVisual: {
      title: "Media Platform Dashboard",
      subtitle: "Live Content Analytics",
      mainStat: "45%",
      mainStatLabel: "Average Subscription Revenue Lift",
      metrics: [
        { label: "Latency", value: "< 2s" },
        { label: "Subscriber Churn", value: "−38%" },
        { label: "Daily Streams", value: "10M+" },
        { label: "Personalisation CTR", value: "+55%" },
      ],
    },
    trustStats: [
      { value: "35+", label: "Media Platforms Delivered", icon: HiRocketLaunch },
      { value: "45%", label: "Avg. Subscription Revenue Lift", icon: HiCurrencyDollar },
      { value: "10M+", label: "Daily Stream Transactions", icon: HiBolt },
      { value: "38%", label: "Lower Subscriber Churn", icon: HiStar },
    ],
    solutions: [
      { icon: HiFilm, title: "OTT / Video Streaming Platform", description: "End-to-end streaming platform with video ingestion, transcoding, adaptive bitrate delivery via CDN, DRM protection, and multi-device playback — built to compete with Netflix-grade UX at a fraction of their infrastructure cost.", href: "/saas-development/multi-tenant-saas-development", color: "from-teal-500 to-cyan-500" },
      { icon: HiDocumentText, title: "Headless Content Management System", description: "API-first CMS for managing articles, video, audio, and interactive content across web, app, and emerging channels — with editorial workflows, content scheduling, and multi-locale support.", href: "/saas-development", color: "from-blue-500 to-indigo-500" },
      { icon: HiCurrencyDollar, title: "Subscription & Paywall Management", description: "Flexible subscription plans, metered paywalls, free-trial flows, dunning automation, and revenue recovery workflows — integrating Stripe with real-time analytics for optimising MRR and reducing failed payment churn.", href: "/saas-development/subscription-platform-development", color: "from-violet-500 to-purple-500" },
      { icon: HiCpuChip, title: "AI Content Recommendation", description: "Collaborative filtering and content-based recommendation engines that drive watch-next engagement, personalise home screens, and increase session depth — reducing churn by keeping subscribers discovering content.", href: "/ai-development/rag-development-services", color: "from-orange-500 to-amber-500" },
      { icon: HiUserGroup, title: "Creator Platform & Monetization", description: "White-label creator platforms with upload tools, subscriber-only content access, live streaming, tipping, paid newsletters, and creator analytics — enabling media brands to launch Substack/Patreon-style products under their own brand.", href: "/saas-development/b2b-saas-development", color: "from-rose-500 to-pink-500" },
      { icon: HiChartBar, title: "Audience Analytics Dashboard", description: "Engagement scoring, content performance analytics, churn prediction models, and A/B testing infrastructure that give editorial and product teams the data to make content and monetisation decisions with confidence.", href: "/ai-development", color: "from-emerald-500 to-teal-500" },
    ],
    painPoints: [
      { icon: HiCloud, title: "CDN Costs and Streaming Latency", description: "Global streaming infrastructure that delivers <2s start times and HD quality to 100K concurrent viewers without a $1M+ CDN bill requires careful architecture. Ad-hoc CDN configurations lead to either performance failures or budget overruns." },
      { icon: HiCurrencyDollar, title: "Subscription Churn and Failed Payments", description: "Average SaaS churn of 5–8% per month is amplified in media, where content freshness expectations are constant. Failed payment recovery — dunning emails, account recovery, and grace periods — can recover 20–30% of churned revenue if automated correctly." },
      { icon: HiDocumentText, title: "Content Rights Management Complexity", description: "Multi-territory content licences, geo-blocking, rental vs. subscription windows, and B2B syndication rights create an access control matrix that manual processes can't enforce. Rights violations carry six-figure licensing penalties." },
      { icon: HiSparkles, title: "Personalisation at Scale", description: "Manually curated editorial feeds don't scale past 10,000 subscribers. Without ML recommendation infrastructure, streaming platforms see session depth plateau — subscribers watch one piece of content, don't discover what's next, and disengage. Every passive viewer is a future churner." },
    ],
    techStack: [
      { label: "React / Next.js", color: "bg-sky-100 text-sky-700 border-sky-200" },
      { label: "Node.js", color: "bg-green-100 text-green-700 border-green-200" },
      { label: "AWS CloudFront / S3", color: "bg-orange-100 text-orange-700 border-orange-200" },
      { label: "PostgreSQL", color: "bg-blue-100 text-blue-700 border-blue-200" },
      { label: "Redis", color: "bg-rose-100 text-rose-700 border-rose-200" },
      { label: "Stripe", color: "bg-violet-100 text-violet-700 border-violet-200" },
      { label: "HLS.js / Video.js", color: "bg-teal-100 text-teal-700 border-teal-200" },
      { label: "Docker / Kubernetes", color: "bg-purple-100 text-purple-700 border-purple-200" },
      { label: "Python / ML", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
      { label: "GraphQL", color: "bg-indigo-100 text-indigo-700 border-indigo-200" },
      { label: "DRM (Widevine / FairPlay)", color: "bg-slate-100 text-slate-700 border-slate-200" },
    ],
    relatedServices: [
      { title: "Subscription Platform Development", description: "Build metered paywalls, tiered subscription plans, and revenue recovery workflows that maximise MRR and reduce churn.", href: "/saas-development/subscription-platform-development", tag: "SaaS Development" },
      { title: "AI Recommendation & RAG Development", description: "Deploy content recommendation engines and semantic search that personalise the viewer experience and drive session depth.", href: "/ai-development/rag-development-services", tag: "AI Development" },
      { title: "Hire Media Platform Engineers", description: "Dedicated engineers with streaming, CMS, and subscription platform experience, available to join your team in 72 hours.", href: "/staff-augmentation", tag: "Staff Augmentation" },
    ],
    faqs: [
      { q: "How do you handle video transcoding and adaptive bitrate streaming?", a: "We architect video pipelines using AWS Elemental MediaConvert or FFmpeg for transcoding, outputting HLS and MPEG-DASH manifests in multiple bitrates (240p to 4K). Content is stored in S3 and delivered via CloudFront CDN with edge caching for sub-2-second start times globally." },
      { q: "Can you implement geo-blocking and content rights enforcement?", a: "Yes. We implement territory-based access control using IP geolocation, user account territory, and content rights metadata. DRM is implemented via Widevine (Android/Web) and FairPlay (iOS/Safari), with licence server integration for time-windowed access." },
      { q: "How does the recommendation engine work?", a: "We implement collaborative filtering (what similar users watched), content-based filtering (content attributes match), and hybrid ensemble models. Initial cold-start is handled with editorial curation and popularity signals. The model retrains incrementally on new viewing data." },
      { q: "How long does it take to build a streaming platform?", a: "A video-on-demand MVP with basic streaming, subscription paywall, and CMS takes 10–14 weeks. A full OTT platform with live streaming, DRM, recommendation engine, and multi-device apps is a 5–8 month engagement." },
      { q: "Can you build a white-label platform for multiple media clients?", a: "Yes — multi-tenant architecture with complete brand isolation, custom domain per client, independent content libraries, and consolidated reporting for platform operators. Several clients run 20+ media brands from a single backend we've built." },
    ],
    bookingStats: [
      { value: "30 min", label: "Discovery session" },
      { value: "Free", label: "No commitment" },
      { value: "35+", label: "Media platforms" },
    ],
    trustItems: [
      "NDA signed before any discussion",
      "Streaming engineers on every call",
      "CDN cost architecture review included",
    ],
    floatingButtonLabel: "Book Media Tech Consultation",
  },
};
